name: 01 - Building Blocks
on: push
jobs:
    Echo-Hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
            - name : Say Goodbye
              run: echo "Goodbye, I will be off"
    Echo-Goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Show the Trigger
              run: echo "I have been triggered by ${{github.event_name}}"