name: 03-Schedule Jobs
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  Cron_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Job
        run: echo "I have been triggered by ${{ github.event_name }}"
